#---------------------------------------------------#
## 配置文件需要放置在 $HOME/.config/clash/config.yml
## 或者运行目录下的config.yml
#---------------------------------------------------#

# HTTP 代理端口
port: 7890
# SOCKS5 代理端口
socks-port: 7891
# HTTP(S) 和 SOCKS 代理混合端口
#mixed-port: 7890 
# Linux 和 macOS 的 redir 代理端口 (如需使用此功能，请取消注释)
#redir-port: 7892
# Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
#tproxy-port: 7893

allow-lan: true # 允许局域网的连接（可用来共享代理）
#bind-address: "*" # 绑定 IP 地址，仅作用于 allow-lan 为 true，'*'表示所有地址

find-process-mode: strict
#  find-process-mode has 3 values:always, strict, off
#  - always, 开启，强制匹配所有进程
#  - strict, 默认，由 mihomo 判断是否开启
#  - off, 不匹配进程，推荐在路由器上使用此模式

mode: Rule # 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）

#自定义 geodata url
#geox-url:
#  geoip: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
#  geosite: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
#  mmdb: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb"
#
#geo-auto-update: false # 是否自动更新 geodata
#geo-update-interval: 24 # 更新间隔，单位：小时

log-level: silent # 日志等级 silent/error/warning/info/debug

#external-controller: 0.0.0.0:9093 # RESTful API 监听地址
#external-controller-tls: 0.0.0.0:9443 # RESTful API HTTPS 监听地址，需要配置 tls 部分配置文件
# secret: "123456" # `Authorization:Bearer ${secret}`

# 您可以将静态网页资源（如 clash-dashboard）放置在一个目录中，clash 将会服务于 `RESTful API/ui`
# 参数应填写配置目录的相对路径或绝对路径。
# http://127.0.0.1:9093/ui/#/
# external-ui: /path/to/ui/folder/
# yacd面板：  https://github.com/haishanh/yacd
# Razord面板：http://clash.razord.top/#/proxies
# external-ui: dashboard

# 实验性功能 hosts, 支持通配符 (例如 *.clash.dev 甚至 *.foo.*.example.com)
# 静态的域名 比 通配域名 具有更高的优先级 (foo.example.com 优先于 *.example.com)
# 注意: hosts 在 fake-ip 模式下不生效
#hosts:
#   '*.clash.dev': 127.0.0.1
#   'alpha.clash.dev': '::1'
tcp-concurrent: true # TCP 并发连接所有 IP, 将使用最快握手的 TCP

dns:
  cache-algorithm: arc
  enable: true # 是否启用dns false
  listen: 0.0.0.0:53
  ipv6: false # false 将返回 AAAA 的空结果
  default-nameserver:
     - 223.5.5.5 # 阿里DNS
     - 119.29.29.29 # 腾讯DNS
     - 180.76.76.76 # 百度DNS
  enhanced-mode: fake-ip # 模式：redir-host或fake-ip
  store-fake-ip: true # 持久化 fake-ip
  fake-ip-range: 198.18.0.1/16 # fake-ip 池设置
  fake-ip-filter: # fake ip 白名单列表，如果你不知道这个参数的作用，请勿修改
     - '*.lan'
     - localhost.ptlogin2.qq.com
    # === Apple Software Update Service ===
     - 'swscan.apple.com'
     - 'mesu.apple.com'
    # === Windows 10 Connnect Detection ===
     - '*.msftconnecttest.com'
     - '*.msftncsi.com'
    # === NTP Service ===
     - 'time.*.com'
     - 'time.*.gov'
     - 'time.*.edu.cn'
     - 'time.*.apple.com'
     - 'time1.*.com'
     - 'time2.*.com'
     - 'time3.*.com'
     - 'time4.*.com'
     - 'time5.*.com'
     - 'time6.*.com'
     - 'time7.*.com'
     - 'ntp.*.com'
     - 'ntp1.*.com'
     - 'ntp2.*.com'
     - 'ntp3.*.com'
     - 'ntp4.*.com'
     - 'ntp5.*.com'
     - 'ntp6.*.com'
     - 'ntp7.*.com'
     - '*.time.edu.cn'
     - '*.ntp.org.cn'
     - '+.pool.ntp.org'
    ## Nintendo Switch
     - '+.srv.nintendo.net'
    ## Sony PlayStation
     - '+.stun.playstation.net'
    ## Microsoft Xbox
     - 'xbox.*.microsoft.com'
     - '+.xboxlive.com'

  # DNS 主要域名配置
  # 支持 UDP，TCP，DoT，DoH，DoQ
  # 这部分为主要 DNS 配置，影响所有直连，确保使用对大陆解析精准的 DNS
  nameserver:
     - 114.114.114.114 # 114DNS
     - 117.50.11.11 # ONE DNS拦截版 恶意网站拦截、广告过滤
     - 117.50.10.10 # ONE DNS纯净版 直接返回其真实的响应结果
     - tls://223.5.5.5:853 # DNS over TLS
     - https://doh.pub/dns-query # DNS over HTTPS
  fallback:
     - 8.8.8.8 # 谷歌DNS
     - 1.1.1.1 # Cloudflare DNS
     - tls://dns.rubyfish.cn:853
     - tls://1.0.0.1:853
     - tls://dns.google:853
     - https://dns.rubyfish.cn/dns-query
     - https://cloudflare-dns.com/dns-query
     - https://dns.google/dns-query
  fallback-filter:
     geoip: true # 配置是否使用 geoip,默认true
     geoip-code: CN # 当 nameserver 域名的 IP 查询 geoip 库为 CN 时，不使用 fallback 中的 DNS 查询结果
     ipcidr: # 在这个网段内的 IP 地址会被考虑为被污染的 IP
       - 240.0.0.0/4

# 1. clash DNS 请求逻辑：
#   (1) 当访问一个域名时， nameserver 与 fallback 列表内的所有服务器并发请求，得到域名对应的 IP 地址。
#   (2) clash 将选取 nameserver 列表内，解析最快的结果。
#   (3) 若解析结果中，IP 地址属于 国外，那么 clash 将选择 fallback 列表内，解析最快的结果。
#
#   因此，我在 nameserver 和 fallback 内都放置了无污染、解析速度较快的国内 DNS 服务器，以达到最快的解析速度。
#   但是 fallback 列表内服务器会用在解析境外网站，为了结果绝对无污染，我仅保留了支持 DoT/DoH 的两个服务器。
#
# 2. clash DNS 配置注意事项：
#   (1) 如果您为了确保 DNS 解析结果无污染，请仅保留列表内以 tls:// 或 https:// 开头的 DNS 服务器，但是通常对于国内域名没有必要。
#   (2) 如果您不在乎可能解析到污染的结果，更加追求速度。请将 nameserver 列表的服务器插入至 fallback 列表内，并移除重复项。
#
# 3. 关于 DNS over HTTPS (DoH) 和 DNS over TLS (DoT) 的选择：
#   对于两项技术双方各执一词，而且会无休止的争论，各有利弊。各位请根据具体需求自行选择，但是配置文件内默认启用 DoT，因为目前国内没有封锁或管制。
#   DoH: 以 https:// 开头的 DNS 服务器。拥有更好的伪装性，且几乎不可能被运营商或网络管理封锁，但查询效率和安全性可能略低。
#   DoT: 以 tls:// 开头的 DNS 服务器。拥有更高的安全性和查询效率，但端口有可能被管制或封锁。
#   若要了解更多关于 DoH/DoT 相关技术，请自行查阅规范文档。
